// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TocHtrainees.Models;

public partial class TocHtrainee
{
    public string Name { get; set; }

    public string Location { get; set; }

    public short? Age { get; set; }
}