// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TocHTraineesSelectionDetails.Models;

public partial class Trainee
{
    [Key]
    public int id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Trainee Name")]
    public string name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string location { get; set; }
}