// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourseManagement.Models;

public partial class Course
{
    [Key]
    public int CourseId { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string CourseName { get; set; }

    public int? CourseDuration { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string Description { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<LessonPlan> LessonPlans { get; set; } = new List<LessonPlan>();
}