// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CourseManagement.Models;

public partial class LessonPlan
{
    [Key]
    public int LessonPlanId { get; set; }

    public int? CourseId { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Date { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Topic { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string Assignment { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Remarks { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("LessonPlans")]
    public virtual Course Course { get; set; }
}